### ISSUE TITLE
[Question] What API does the plugin use under Android?

### ISSUE THREAD

**Issue by SerQuicky** [transistorsoft/capacitor-background-fetch#1]
Hello @christocracy,

first of all, I want to thank you for this great plugin. I just have a general question on how the plugin creates the background tasks under android. I do understand, that it uses the Background Tasks API under iOS. Does it use the WorkManager API under Android or another API?

**Comment by christocracy** [comment]
What background-tasks are you referring?  The one from `startBackgroundTask`?

**Comment by SerQuicky** [comment]
If I use your Angular-Example and schedule the task with `initBackgroundFetch` it works completely fine, but I don't really understand what Android-API it uses under the hood (Services, WorkManager, etc.).

**Comment by christocracy** [comment]
Sorry, I thought we were at the background-geolocation repo.  I see this is background-fetch.

This plugin uses JobScheduler for sdk >= lollipop and AlarmManager for everything less.

This is essentially what WorkManager is.  WorkManager is merely a wrapper for JobScheduler + AlarmManager.
