### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by pauldev20** [transistorsoft/capacitor-background-fetch#14]
## Your Environment
* Plugin version: 1.0.2
* Platform: iOS
* Device OS version: iOS 16.3
* Device manufacturer / model: iPhone 13 Pro Max
* XCode version: 14.2
* Capacitor info (`npx cap doctor`)
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/android: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```
* Plugin config provided to `BackgroundFetch.configure`: N/A

## Expected Behavior

Should not show any warnings/errors about parsing the source map.

## Actual Behavior

Throwing multiple warnings:
```
[react-scripts] WARNING in ./node_modules/@transistorsoft/capacitor-background-fetch/dist/esm/definitions.js
[react-scripts] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[react-scripts] Failed to parse source map from '.../node_modules/@transistorsoft/capacitor-background-fetch/src/definitions.ts' file: Error: ENOENT: no such file or directory, open '.../node_modules/@transistorsoft/capacitor-background-fetch/src/definitions.ts'
[react-scripts] WARNING in ./node_modules/@transistorsoft/capacitor-background-fetch/dist/esm/index.js
[react-scripts] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[react-scripts] Failed to parse source map from '.../node_modules/@transistorsoft/capacitor-background-fetch/src/index.ts' file: Error: ENOENT: no such file or directory, open '.../node_modules/@transistorsoft/capacitor-background-fetch/src/index.ts'
[react-scripts] webpack compiled with 2 warnings
```

## Steps to Reproduce

1. `npm i @transistorsoft/capacitor-background-fetch`
2. `npx cap sync`
3. `ionic capacitor run ios -l --external --open`

## Context

Run the app in development mode on iOS

**Comment by christocracy** [comment]
Try building the /example app in this repo.

**Comment by pauldev20** [comment]
The /example app doesn't throw these warnings. I used React and not Angular, so the issue seams to be a problem with React.

**Comment by christocracy** [comment]
I don't think React has anything to do with it.

What's with these paths with triple-dots:  `'.../node_modules`?

I suggest you generate a simple HellowWorld app and attempt to reproduce this.  I suspect you won't be able to.

**Comment by pauldev20** [comment]
I just added those triple dots to not need to paste my complete path here, because it would have been really long. So the `.../node_modules` folder is just the node_modules folder inside the root folder of my project.

So I tried creating a fresh Ionic React app and installing the plugin via: `npm install --save @transistorsoft/capacitor-background-fetch` and I am still receiving the same warnings as soon as using the plugin.

**Comment by christocracy** [comment]
Did you follow the directions of the `/example` [README](https://github.com/transistorsoft/capacitor-background-fetch/tree/master/example)?

You need to manually compile the plugin's typescript when cloning this repo to run the /example.

**Comment by pauldev20** [comment]
Yes, I did follow all the steps, but sadly it didn't work.

**Comment by mattsbennett** [comment]
We have these warnings in an ionic react app as well

**Comment by christocracy** [comment]
Create for me a simple *HelloWorld* app which reproduces this.

**Comment by aidanm1999** [comment]
Hi guys, this issue persists. Any thoughts @christocracy?
