### ISSUE TITLE
Information request: execute headless task when app is active?

### ISSUE THREAD

**Issue by Ryner47** [transistorsoft/capacitor-background-fetch#15]
## Your Environment
* Plugin version: 1.0.3
* Platform: Android
* Device OS version: Android 10
* Capacitor info (`npx cap doctor`)

Latest Dependencies:
@capacitor/cli: 4.7.1
@capacitor/core: 4.7.1
@capacitor/android: 4.7.1
@capacitor/ios: 4.7.1

Installed Dependencies:
@capacitor/ios: not installed
@capacitor/core: 4.7.0
@capacitor/cli: 4.7.0
@capacitor/android: 4.7.0

* Plugin config provided to `BackgroundFetch.configure`:

```
BackgroundFetch.configure({
	minimumFetchInterval: 15,
	stopOnTerminate: false,
	enableHeadless: true,
	startOnBoot: true,
	requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY
},
```

## Context
Hello, 
I configured the plugin for my android app and it works perfectly in headless mode too.

At this point I would like to ask for a clarification.
Considering that:
- if app is terminated it is executed what is implemented in the 'BackgroundFetchHeadlessTask.java' class
- if app is active or paused (background) it is executed what is implemented in the 'performYourWorkHere' (for example) method defined inside 'BackgroundFetch.configure' configuration

Is it possible to somehow force the 'BackgroundFetchHeadlessTask' to run even when the app is active or paused?
I would like to understand if it is possible in such a way as to centralize the logic only in 'BackgroundFetchHeadlessTask.java' class.
Thanks

**Comment by christocracy** [comment]
> Is it possible to somehow force the 'BackgroundFetchHeadlessTask' to run even when the app is active or paused?

No.  Headless = app terminated (where your Capacitor JavaScript app no longer exists).
