### ISSUE TITLE
background-fetch clashes with native custom IOS background Tasks

### ISSUE THREAD

**Issue by SchallerStefan** [transistorsoft/capacitor-background-fetch#17]
## Your Environment
* Plugin version: "@transistorsoft/capacitor-background-fetch": "^1.0.3"
* Platform: iOS
* Device OS version: 16.3.1
* Device manufacturer / model: iPhone Xs
* XCode version: 14.3
* Capacitor info (`npx cap doctor`)
@capacitor/android: 4.7.1
@capacitor/core: 4.7.1
@capacitor/ios: 4.7.1
@capacitor/cli: 4.7.1
* Plugin config provided to `BackgroundFetch.configure`:
-
## Expected Behavior

In our Capacitor-App we need to refresh our refresh-Token every 2 weeks. In Android I used a "PeriodicWorkRequest" which worked just fine. On IOS I tried using backgroundTasks:
"https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app"
I expected this to work independently from the background-fetch-plugin.

## Actual Behavior
Upon putting our own taskId in "Permitted background task scheduler identifiers" and registering it in "didFinishLaunchingWithOptions" using `BGTaskScheduler.shared.register` it clashes with the "capacitor-background-fetch"-Plugin. (Error is "task launcher for task with com... has already been registered")

## Steps to Reproduce

1. Put custom taskId in "Permitted background task scheduler identifiers"
2. Register it in Method "didFinishLaunchingWithOptions" using `BGTaskScheduler.shared.register`

## Context
The plugin probably registers all strings in "Permitted background task scheduler identifiers" because of `BackgroundFetch.scheduleTask`.
I would use scheduleTask if it was a simple Background-Fetch and not use Background-processing (because it needs the phone to be connected and has more restrictions than fetch). The Background-Fetch-Plugin asks periodically, but I would like to control when the Background-Task is submitted myself.

My questions concerning this are:
1. Can I in some way bypass the Background-Fetch-Plugin and have complete native control ourselves (maybe try/catch the initialization of the plugin in "didFinishLaunchingWithOptions"?)
2. Does the Background-Fetch (not scheduleTask) use the same implementation as described in
"https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app"
If so, can I simply submit the custom Task myself with "BGTaskScheduler.shared.submit(request)" (where request has the custom taskId) or will this result in a backgroundProcess all the same?
3. If both options are not really good, can I simply configure the Background-Fetch-Plugin with a minimumFetchInterval of 2 weeks and it would not clash with the Background-geolocation-plugin (it would use the same taskId "com.transistorsoft.fetch" so Im worried, that the geolocation would then also only update every 2 weeks)?

**Comment by christocracy** [comment]
>On IOS I tried using backgroundTasks:
"https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app"
>I expected this to work independently from the background-fetch-plugin.

This is the same API implemented by `background_fetch` (including the `.scheduleTask` method).

There is no need to implement the [iOS `BGTaskScheduler`](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler?language=objc) API manually.  

Everything about the iOS `BGTaskScheduler` API is implemented by `background-fetch`.

**Comment by christocracy** [comment]
An app is only allowed to register one iOS "background refresh" task.

There is only one instance of the `BackgroundFetch` instance.  It is shared by both `background-fetch` and `background-geolocation`.

**Comment by christocracy** [comment]
>Is that because scheduleTask is a BGProcessingTask instead of a BGAppRefreshTask?

Yes.  It doesn't matter if you implement `BGProcessingTask` with your own native code vs using `background-fetch`.

iOS simply doesn't seem to run `BGProcessingTask` unless the device is plugged-in to power.  Apple may change this behaviour with future iOS updates.  That's up to Apple.

**Comment by SchallerStefan** [comment]
Ok, thank you again!
