### ISSUE TITLE
Capacitor 5 support?

### ISSUE THREAD

**Issue by cleverfleet** [transistorsoft/capacitor-background-fetch#19]
We use background fetch together with @transistorsoft/capacitor-background-geolocation in a project. 
We cannot update to Capacitor 5.x as background fetch defines Capacitor 4 as a dependency. Is this a technical reason or can this be fixed? Thanks a lot!

Plugin Version: 1.0.4

Latest Dependencies:

  @capacitor/cli: 5.0.2
  @capacitor/core: 5.0.2
  @capacitor/android: 5.0.2
  @capacitor/ios: 5.0.2

Installed Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/ios: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0

[success] Android looking great! 👌

**Comment by christocracy** [comment]
Released:
- `capacitor-background-fetch: 5.0.0`
- `capacitor-background-geolocation: 5.0.0`

**Comment by cleverfleet** [comment]
great, that was fast, thanks a lot!
