### ISSUE TITLE
Error calling method ready on plugin BackgroundGeolocation: No method found.

### ISSUE THREAD

**Issue by ArtN0nymous** [transistorsoft/capacitor-background-fetch#27]
## Your Environment
* Plugin version: 5.4.2
* Platform: iOS
* Device OS version: 17.2
* Device manufacturer / model: iPhone 15 Pro Max
* XCode version: 15.2
* Capacitor info (`npx cap doctor`)
* Installed Dependencies:

  @capacitor/cli: 5.0.3
  @capacitor/core: 5.0.3
  @capacitor/android: 5.0.3
  @capacitor/ios: 5.0.3
* Plugin config provided to `BackgroundFetch.configure`: None
*     BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 50,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,
      locationTimeout: 60,
      locationUpdateInterval: 10000,
      heartbeatInterval: 60,
      disableElasticity: true,
      stopOnStationary: true,
      showsBackgroundLocationIndicator: true,
      disableMotionActivityUpdates: true,
      preventSuspend: true,
      allowIdenticalLocations: false,
      url: environment.urlServidor + 'api/v1/get-project/' + localStorage.getItem('current_project'),
      headers: { Authorization: 'Bearer ' + localStorage.getItem('token')},
      // locationUpdateInterval: 10000,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
    })

## Expected Behavior
I need to track the location of devices in the background while validating whether the current location of the device is within a certain area (the range of the area is determined on the server side). For this last, I use requests to the server which responds by validating the coordinates sent, this in the onLocation event

## Actual Behavior
On Android it works correctly, however, when testing in an iPhone simulator when trying to start the plugin it does not seem to start correctly and does not return information about the location. Reviewing the logs in xCode you can see that it says: " ⚡️ To Native -> BackgroundGeolocation addListener 6821814 ⚡️ To Native -> BackgroundGeolocation addListener 6821815 ⚡️ To Native -> BackgroundGeolocation addListener 6821816 ⚡️ To Native -> BackgroundGeolocation addListener 682181 7 ⚡️ To Native -> BackgroundGeolocation addListener 6821818 ⚡️ To Native -> BackgroundGeolocation ready 6821819 ⚡️ Error calling method ready on plugin BackgroundGeolocation: No method found ⚡️ Ensure plugin method exists and uses @objc in its declaration, and has been defined"

## Steps to Reproduce
1. Try to call BackGroundGeolocation.ready();

## Context
Trying to start the plugin in iOS platform.

## Debug logs
- ios XCode logs
- [TSBackgroundFetch load]: (
)
[TSBGAppRefreshSubscriber load]: {
}
WARNING: appId set, but please call setLaunchOptions(launchOptions) to complete OneSignal init!
nw_connection_copy_connected_local_endpoint_block_invoke [C1] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C1] Connection has no local endpoint
no client id found in config
KeyboardPlugin: no resize
⚡️  Loading app at capacitor://localhost...
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
nw_connection_copy_connected_local_endpoint_block_invoke [C5] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
nw_connection_copy_connected_remote_endpoint_block_invoke [C5] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
nw_connection_copy_protocol_metadata_internal_block_invoke [C5] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
nw_connection_copy_connected_local_endpoint_block_invoke [C3] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C3] Connection has no local endpoint
⚡️  [log] - onscript loading complete
⚡️  [warn] - Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading
⚡️  To Native ->  CapacitorHttp request 17078862
⚡️  WebView loaded
To Native Cordova ->  OneSignalPush getDeviceState OneSignalPush ["options": []]
To Native Cordova ->  OneSignalPush init OneSignalPush ["options": []]
To Native Cordova ->  OneSignalPush setNotificationOpenedHandler OneSignalPush ["options": []]
To Native Cordova ->  OneSignalPush promptForPushNotificationsWithUserResponse OneSignalPush ["options": [0]]
⚡️  To Native ->  Geolocation checkPermissions 17078863
⚡️  TO JS {"coarseLocation":"granted","location":"granted"}
⚡️  [log] - Ionic Native: deviceready event fired after 43 ms
⚡️  To Native ->  StatusBar setOverlaysWebView 17078864
ERROR MESSAGE:  {"data":{},"message":"not implemented","errorMessage":"not implemented","code":"UNIMPLEMENTED"}
⚡️  To Native ->  Geolocation getCurrentPosition 17078865
⚡️  [log] - User accepted notifications: true
⚡️  [error] - {"data":{},"message":"not implemented","errorMessage":"not implemented","code":"UNIMPLEMENTED"}
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: not implemented
de@capacitor://localhost/main.a9588408ba23a7f7.js:1:412
returnResult@user-script:2:766:49
@user-script:2:748:29
⚡️  To Native ->  Geolocation requestPermissions 17078866
⚡️  TO JS {"location":"granted","coarseLocation":"granted"}
nw_connection_copy_connected_local_endpoint_block_invoke [C8] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
nw_connection_copy_connected_remote_endpoint_block_invoke [C8] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
nw_connection_copy_protocol_metadata_internal_block_invoke [C8] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
nw_connection_copy_connected_local_endpoint_block_invoke [C6] Connection has no local endpoint
nw_connection_copy_connected_local_endpoint_block_invoke [C6] Connection has no local endpoint
⚡️  To Native ->  App addListener 17078867
⚡️  To Native ->  Keyboard getResizeMode 17078868
⚡️  TO JS {"mode":"none"}
⚡️  TO JS {"status":200,"url":"https:\/\/maps.googleapis.com\/maps\/api\/mapsjs\/gen_204?csp_test=true","data":{},"headers":{"Content-Length":"23","Server":"scaffolding on HTTPServer2","x-xss-protection":"0","Date":"Tue, 27 Aug 2024 17:25:45 GMT","Vary":"Origin, X-O

⚡️  [log] - On init home page
⚡️  [log] - After content init home page
⚡️  [log] - Start Background Geolocation
⚡️  To Native ->  BackgroundGeolocation addListener 17078869
⚡️  To Native ->  BackgroundGeolocation addListener 17078870
⚡️  To Native ->  BackgroundGeolocation addListener 17078871
⚡️  To Native ->  BackgroundGeolocation addListener 17078872
⚡️  To Native ->  BackgroundGeolocation addListener 17078873
⚡️  To Native ->  BackgroundGeolocation ready 17078874
⚡️  Error calling method ready on plugin BackgroundGeolocation: No method found.
⚡️  Ensure plugin method exists and uses @objc in its declaration, and has been defined
⚡️  To Native ->  Keyboard getResizeMode 17078875
⚡️  TO JS {"mode":"none"}
⚡️  To Native ->  CapacitorHttp request 17078876
⚡️  To Native ->  CapacitorHttp request 17078877

⚡️  TO JS {"status":200,"headers":{"Cache-Control":"no-cache, private","X-Powered-By":"PHP\/8.2.12","Host":"192.168.1.22:8000","Date":"Tue, 27 Aug 2024 17:25:51 GMT","X-RateLimit-Limit":"60","X-RateLimit-Remaining":"59","Access-Control-Allow-Origin":"*","Content-Typ

⚡️  TO JS {"url":"http:\/\/192.168.1.22:8000\/api\/v1\/my-projects","data":{"status":"success","data":[{

ERROR MESSAGE:  {"errorMessage":"The operation couldn’t be completed. (kCLErrorDomain error 0.)","message":"The operation couldn’t be completed. (kCLErrorDomain error 0.)"}
⚡️  [error] - {"errorMessage":"The operation couldn’t be completed. (kCLErrorDomain error 0.)","message":"The operation couldn’t be completed. (kCLErrorDomain error 0.)"}
⚡️  [log] - {"errorMessage":"The operation couldn’t be completed. (kCLErrorDomain error 0.)"}

- use #getLog #emailLog methods (@see docs)
⚡️  [error] - ERROR Error: Uncaught (in promise): TypeError: ye.getLog is not a function. (In 'ye.getLog({options:ot})', 'ye.getLog' is undefined)
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:136865
e@capacitor://localhost/polyfills.0731a7263f6e07b2.js:1:18436
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:136839
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:156583
u@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:774503
de@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:774722
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:774794
e@capacitor://localhost/polyfills.0731a7263f6e07b2.js:1:18436
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:774667
ngAfterContentInit@capacitor://localhost/2080.df1b93d250411620.js:1:1929
i@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:488488
l@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:488631
c@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:488391
Cn@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:488111
pc@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:527941
fc@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:527067
detectChanges@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:530192
setActive@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:737122
activateWith@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:744020
activateRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:661266
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660381
forEach@[native code]
activateChildRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660356
activateRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:661357
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660381
forEach@[native code]
activateChildRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660356
activateRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:661306
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660381
forEach@[native code]
activateChildRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660356
activateRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:661357
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660381
forEach@[native code]
activateChildRoutes@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:660356
activate@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:658994
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:684600
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:420669
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:419749
next@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:411261
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:630519
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:419749
next@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:411261
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:420662
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:419749
next@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:411261
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:419749
next@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:411261
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:420662
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:419749
next@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:411261
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:418565
_trySubscribe@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:407866
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:407811
ze@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:423890
subscribe@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:407705
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:420640
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:425535
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:407762
ze@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:423890
subscribe@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:407705
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:421869
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:419749
next@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:411261
@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:419749
next@capacitor://localhost/main.5c36b5ee9d17b02f.js:1:411261
@capacitor://localhost/ma
-->

**Comment by christocracy** [comment]
Your app thinks the plug-in is not installed.

I suggest you first practice installing and setting up the plugin in a simple hello-world app.

**Comment by christocracy** [comment]
Why are you posting an error from background-geolocation at the background-fetch repo?
