### ISSUE TITLE
Update docs for testing: Just use option from Debug menu to Simulate Background Fetch

### ISSUE THREAD

**Issue by GeroldSchierholz** [transistorsoft/capacitor-background-fetch#3]
Update docs for testing: Just use option from Debug menu to Simulate Background Fetch
![image](https://user-images.githubusercontent.com/16380657/122905567-9f199e00-d351-11eb-96f8-0c3c00c58fe4.png)

Hope this helps.

**Comment by christocracy** [comment]
That only tests the deprecated pre iOS 13 mechanism.  It does not test the new iOS 13+ mechanism.
