### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'.

### ISSUE THREAD

**Issue by vkyeswa** [transistorsoft/capacitor-background-fetch#4]
## Your Environment
* Plugin version: 0.0.6
* Platform: Android
* OS version:10
* Device manufacturer / model: Pixel 4 (Emulator)
* Capacitor Version : 3
* Plugin config provided to `BackgroundFetch.configure`:
```javascript <!-- syntax-highlighting:  paste your code below -->
{
      minimumFetchInterval: 15,
      startOnBoot: true,
    }
```

## Expected Behavior
Successful build and run

## Actual Behavior
Execution failed for task ':app:checkDebugAarMetadata'.
Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
## Steps to Reproduce

1. npm install --save @transistorsoft/capacitor-background-fetch
2.npx cap sync
3.ionic cap open android
4.run in android studio

## Context

Test on Android

## Debug logs
<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/../apps/../android/capacitor-cordova-android-plugins/src/main/libs/
       - file:/Users/../apps/../android/app/libs/
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :transistorsoft-capacitor-background-fetch

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

</details>

**Comment by christocracy** [comment]
You did not follow the **required** Android Setup Instructions in the readme.
