### ISSUE TITLE
Archving on xcode fails with an error message could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64

### ISSUE THREAD

**Issue by scottieslg** [transistorsoft/capacitor-background-fetch#6]
## Your Environment
* Plugin version: 0.0.6
* Platform: iOS
* Device OS version: 12.3
* XCode version: 12.4
* Capacitor info (`npx cap doctor`)
* Latest Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/ios: 3.1.2

Installed Dependencies:

  @capacitor/cli: 3.1.2
  @capacitor/android: 3.1.2
  @capacitor/core: 3.1.2
  @capacitor/ios: 3.1.2

## Expected Behavior
When archiving for release, XCode should archive successfully

## Actual Behavior
XCode fails the archive with an error

## Steps to Reproduce
1. Add both @transistorsoft/capacitor-background-fetch and @transistorsoft/capacitor-background-geolocation to package.json
2. run npx cap sync ios
3. run npx cap open ios
4. In Xcode, run Archive

## Context
Trying to add the capacitor plugins and release to the app store.  The build fails with an error.

If I remove these packages, it builds fine.

## Debug logs
Error: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/App normal (in target 'App' from project 'App')
    cd /Users/myuser/src/Skedit/angular/ios/App
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios12.3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -L/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/Capacitor -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorApp -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorCamera -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorCordova -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorFilesystem -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorHaptics -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorKeyboard -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorSplashScreen -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorStatusBar -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CocoaLumberjack -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CordovaPlugins -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/TransistorsoftCapacitorBackgroundFetch -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/TransistorsoftCapacitorBackgroundGeolocation -F/Users/myuser/src/Skedit/angular/ios/App/Pods/../../../node_modules/@transistorsoft/capacitor-background-fetch/ios -F/Users/myuser/src/Skedit/angular/ios/App/Pods/../../../node_modules/@transistorsoft/capacitor-background-geolocation/ios -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/TSBackgroundFetch -F/Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/TSLocationManager -filelist /Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/App.build/Objects-normal/arm64/App.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/App.build/Objects-normal/arm64/App_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos -Xlinker -final_output -Xlinker /Applications/App.app/App -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/App.build/Objects-normal/arm64/App.swiftmodule -ObjC -lsqlite3 -lz -framework Accelerate -framework Capacitor -framework CapacitorApp -framework CapacitorCamera -framework CapacitorFilesystem -framework CapacitorHaptics -framework CapacitorKeyboard -framework CapacitorSplashScreen -framework CapacitorStatusBar -framework CocoaLumberjack -framework Cordova -framework CordovaPlugins -framework CoreGraphics -framework Foundation -framework ImageIO -framework MessageUI -framework Photos -framework QuartzCore -framework Security -framework SystemConfiguration -framework TSBackgroundFetch -framework TSLocationManager -framework TransistorsoftCapacitorBackgroundFetch -framework TransistorsoftCapacitorBackgroundGeolocation -framework UIKit -framework WebKit -framework Pods_App -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/App.build/Objects-normal/arm64/App_dependency_info.dat -o /Users/myuser/Library/Developer/Xcode/DerivedData/App-batmmbhaomsovpfatyecjbkvhmcu/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/App

**Comment by christocracy** [comment]
This library was built with XCode 12.5

**Comment by scottieslg** [comment]
Upgrading to BigSur and XCode 12.5 fixed this.
